// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Button$ReactHooksTemplate = require("./Button.bs.js");

function str(prim) {
  return prim;
}

function App(Props) {
  var match = React.useReducer((function (state, action) {
          if (action) {
            return /* record */[/* count */state[/* count */0] - 1 | 0];
          } else {
            return /* record */[/* count */state[/* count */0] + 1 | 0];
          }
        }), /* record */[/* count */0]);
  var dispatch = match[1];
  var count = match[0][/* count */0];
  var incrementCounter = function (param) {
    return Curry._1(dispatch, /* INCREMENT */0);
  };
  var decrementCounter = function (param) {
    return Curry._1(dispatch, /* DECREMENT */1);
  };
  console.log("counter", count);
  return React.createElement("div", undefined, React.createElement("h2", undefined, "The Counter App"), React.createElement("hr", undefined), React.createElement(Button$ReactHooksTemplate.make, {
                  operation: incrementCounter,
                  label: "INCREMENT"
                }), React.createElement("div", {
                  className: "counter"
                }, React.createElement("h4", undefined, "counter: ", React.createElement("span", undefined, String(count)))), React.createElement(Button$ReactHooksTemplate.make, {
                  operation: decrementCounter,
                  label: "DECREMENT"
                }));
}

var make = App;

exports.str = str;
exports.make = make;
/* react Not a pure module */
