// Generated by BUCKLESCRIPT VERSION 5.0.2, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function str(prim) {
  return prim;
}

function Button(Props) {
  var operation = Props.operation;
  var label = Props.label;
  return React.createElement("button", {
              onClick: (function (_e) {
                  return Curry._1(operation, /* () */0);
                })
            }, label);
}

var make = Button;

exports.str = str;
exports.make = make;
/* react Not a pure module */
